### ISSUE TITLE
使用量的`start_date`为本月第一天，实际应范围更大，金额更多

### ISSUE THREAD

**Issue by imldy** [ClarenceDan/openai-billing#1]
后期补充：代码功能没啥问题，在绑卡后 查询用量的`start_date`为本月第一天 是正常的。

乌龙了

只是判断逻辑不太完美……不过还是非常感谢

**Comment by imldy** [comment]
看起来最好修改判断是否是每月重置额度的方法，`subscriptionData`存在`has_payment_method`key可以用来判断是否绑卡，绑卡后就是每月重置额度了。

不过因为目前一旦绑卡，额度肯定大于20，当前好像也没啥问题。

https://github.com/ClarenceDan/openai-billing/blob/59b018314281b816b6bdfb303c378f4e101b4c03/checkbilling.html#L408-L411

**Comment by ClarenceDan** [comment]
近期更新一波，支持检测GPT-4
